version: '3.1'

services:
  localdb:
   ports:
     - "53306:3306"
   image: mariadb
   command: --character-set-server=utf8 --collation-server=utf8_general_ci
   container_name: infra_mysqldb
   volumes:
     - "$PWD/db/data:/var/lib/mysql"
   environment:
       MYSQL_ROOT_PASSWORD: mysqlvotmdnjem
       MYSQL_DATABASE: default
       MYSQL_USER: default
       MYSQL_PASSWORD: default
   healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
       timeout: 20s
       retries: 10

  redis1:
    image: redis:latest
    container_name: infra_redis_master
    ports:
      - "56379:6379"
    healthcheck:
       test: "redis-cli -h 127.0.0.1 ping"
       interval: 3s
       timeout: 1s
       retries: 5

  redis2:
    image: redis:latest
    container_name: infra_redis_slave
    ports:
      - "56380:6379"
    command: ["redis-server", "--port", "6379", "--replicaof", "infra_redis_master", "6379"]
    healthcheck:
       test: "redis-cli -h 127.0.0.1 ping"
       interval: 3s
       timeout: 1s
       retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: infra_redis_commander
    environment:
      - REDIS_HOSTS=redis_store:infra_redis_master:6379
    ports:
      - "59081:8081"

  mq:
    image: rabbitmq:management
    container_name: infra_mq
    ports:
      - "55672:5672"
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=cbteam
      - RABBITMQ_DEFAULT_PASS=cbteampass
