customCommands:
  - key: '<c-f>'
    context: 'localBranches'
    command: 'git pull --prune'
    description: 'Pull with prune'
  - key: '<c-t>'
    context: 'tags'
    command: 'git fetch --prune origin "+refs/tags/*:refs/tags/*"'
    description: 'Fetch prune with tags'
git:
  branchLogCmd: "git log --graph --abbrev=7 --decorate --date=relative --color=always --format=format:'%C(bold red)%h%C(reset) -%C(bold yellow)%d%C(reset)%C(white)%w(110,1,2)%s%C(reset) %C(reset)%C(bold green)(%ar)%C(reset) %C(bold blue)<%an>%Creset' --all"
gui:
  nerdFontsVersion: "3"
os:
  edit: 'nvr -O {{filename}}; nvr --remote-send "<c-w>o<cr>:set nu<cr>"'
  editAtLine: 'nvr -O {{filename}}; nvr --remote-send "<c-w>o<cr>:{{line}}<CR>:set nu<cr>"'
  editAtLineAndWait: 'nvim +{{line}} {{filename}}'
confirmOnQuit: false
quitOnTopLevelReturn: true
promptToReturnFromSubprocess: false
